module.exports=[
    {
        "roll_no": "2K21\/B7\/53",
        "fullname": "HARDIK  ",
        "stu_id": 198839,
        "reg_dtu": "DTU",
        "reg_year": 2021,
        "reg_group": "B7",
        "reg_id": 53,
        "f_name": "HARDIK",
        "fathername": "RISHI PARKASH",
        "rank": "NULL",
        "scheme_year": 2021,
        "sp_code": "EE",
        "aprog": "PHD",
        "photo": "NULL",
        "phone": 9991468093,
        "email": "kaushikhardik35@gmail.com",
        "address": "567,SECTOR 23,SONIPAT,SONIPAT,HARYANA    131001",
        "city": "NULL",
        "pincode": "NULL",
        "hindiname": "NULL",
        "sex": "M",
        "category": "General",
        "dob": "12\/13\/2003",
        "gatescore": "NULL",
        "mothername": "SUMAN",
        "comment": "NULL",
        "secid": 0,
        "bg": "NULL",
        "libno": "NULL",
        "campus": "MN",
        "nationality": "INDIAN",
        "f_phone": 9991468093,
        "m_phone": "NULL",
        "dtu_email": "hardik_ee21b7_53@dtu.ac.in"
       }
]